### ISSUE TITLE
Error in goingnative FOR THE SAKE OF ARGUMENT

### ISSUE THREAD

**Issue by benplain** [nodeschool/discussions#1458]
Hi,

I am having trouble with this exercise.

Here is the output after verifying.

```
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
2015-09-21 14:42:14.441 xcodebuild[5422:1007] [MT] PluginLoading: Required plug-in compatibility UUID A16FF353-8441-459E-A50C-B071F53F51B7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/myaddon/myaddon.o
../myaddon.cc:8:3: error: no template named 'Local' in namespace 'Nan'; did you mean simply 'Local'?
  Nan::Local<Function> str;
  ^~~~~~~~~~
  Local
/Users/user/.node-gyp/4.0.0/deps/v8/include/v8.h:768:34: note: 'Local' declared here
  template<class F> friend class Local;
                                 ^
/Users/user/.node-gyp/4.0.0/deps/v8/include/v8.h:364:15: error: assigning to 'v8::Function *' from incompatible type 'v8::String *'
    out->val_ = IsEmpty() ? nullptr : this->val_;
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../myaddon.cc:9:15: note: in instantiation of function template specialization 'v8::MaybeLocal<v8::String>::ToLocal<v8::Function>' requested here
  if(maybeStr.ToLocal(&str)) {
              ^
2 errors generated.
make: *** [Release/obj.target/myaddon/myaddon.o] Error 1
✗ node-gyp build: `make` failed with exit code: 2

# FAIL

Your solution to FOR THE SAKE OF ARGUMENT didn't pass. Try again!
```

Here is the addon.cc

```
#include <nan.h>

using namespace v8;


NAN_METHOD(Print) {
  Nan::MaybeLocal<String> maybeStr = Nan::To<String>(info[0]);
  Nan::Local<Function> str;
  if(maybeStr.ToLocal(&str)) {
    Nan::ThrowError("Error converting first argument to string");
  }
  printf("%s\n", *String::Utf8Value(str));
}

NAN_MODULE_INIT(Init) {
  Nan::Set(target, Nan::New("print").ToLocalChecked(),
      Nan::GetFunction(Nan::New<FunctionTemplate>(Print)).ToLocalChecked());
}

NODE_MODULE(myaddon, Init)
```

node: v4.0.0
node-gyp: v2.0.2
nan: v2.0.9

Has anyone run into this or able to shed any light on why I am getting that?

**Comment by SomeoneWeird** [comment]
Oops! That's my bad. Try changing `Nan::Local<Function>` to `v8::Local<Function>`.

**Comment by SomeoneWeird** [comment]
I just pushed a fix, many thanks!

**Comment by benplain** [comment]
Thanks @SomeoneWeird 

Now I am getting this
```
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
2015-09-21 17:18:25.682 xcodebuild[6215:1007] [MT] PluginLoading: Required plug-in compatibility UUID A16FF353-8441-459E-A50C-B071F53F51B7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/myaddon/myaddon.o
In file included from ../myaddon.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/user/.node-gyp/4.0.0/src/node.h:42:
/Users/user/.node-gyp/4.0.0/deps/v8/include/v8.h:364:15: error: assigning to 'v8::Function *' from incompatible type 'v8::String *'
    out->val_ = IsEmpty() ? nullptr : this->val_;
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../myaddon.cc:9:15: note: in instantiation of function template specialization 'v8::MaybeLocal<v8::String>::ToLocal<v8::Function>' requested here
  if(maybeStr.ToLocal(&str)) {
              ^
1 error generated.
make: *** [Release/obj.target/myaddon/myaddon.o] Error 1
✗ node-gyp build: `make` failed with exit code: 2

# FAIL

Your solution to FOR THE SAKE OF ARGUMENT didn't pass. Try again!
```

Cheers

**Comment by SomeoneWeird** [comment]
@benplain Now I understand why I never code after a 12 hour plane flight - change `v8::Local<Function>` to `v8::Local<String>`

**Comment by benplain** [comment]
Thanks @SomeoneWeird

I tried that initially and the node-gyp rebuilds properly but `goingnative verify myaddon` still fails with the error in the original issue post.

```
../myaddon.cc:7:3: error: no template named 'Local' in namespace 'Nan'; did you mean simply 'Local'?
  Nan::Local<Function> str;
  ^~~~~~~~~~
  Local
```

**Comment by benplain** [comment]
sorry here is my new myaddon.cc
```
#include <nan.h>

using namespace v8;


NAN_METHOD(Print) {
  Nan::MaybeLocal<String> maybeStr = Nan::To<String>(info[0]);
  v8::Local<String> str;
  if(maybeStr.ToLocal(&str)) {
    Nan::ThrowError("Error converting first argument to string");
  }
  printf("%s\n", *String::Utf8Value(str));
}

NAN_MODULE_INIT(Init) {
  Nan::Set(target, Nan::New("print").ToLocalChecked(),
      Nan::GetFunction(Nan::New<FunctionTemplate>(Print)).ToLocalChecked());
}

NODE_MODULE(myaddon, Init)
```

**Comment by SomeoneWeird** [comment]
Ah yes. It's still trying to use the wrong file as the new one hasn't been published to npm yet. You can manually go in and change that file to be correct, or you can can uninstall goingnative and run `npm install workshopper/goingnative` (be aware you should only do this temporarily while the patched version is not out)

**Comment by benplain** [comment]
Great. Thanks @SomeoneWeird
